paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200930-Trex293CISD2-Caff-Ionomycin\\20200930-2"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200930-Trex293CISD2-Caff-Ionomycin\\20200930-2\\Response"
constants:
  example_bool: False
  baseline_response_start_time: 110
  baseline_response_end_time: 140
  response_start_time: 140
  response_end_time: 210
  baseline_ionomycin_start_time: 200
  baseline_ionomycin_end_time: 230
  ionomycin_start_time: 230
  ionomycin_end_time: 340
