paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20211108_HeLaCISD2_ATP_DR_1"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20211108_HeLaCISD2_ATP_DR_1\\Response"
constants:
  baseline_response_start_time: 50
  baseline_response_end_time: 80
  response_start_time: 85
  response_end_time: 400
