paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200930-Trex293CISD2-Caff-Ionomycin\\20200930-1"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200930-Trex293CISD2-Caff-Ionomycin\\20200930-1\\Response"
constants:
  example_bool: False
  baseline_response_start_time: 120
  baseline_response_end_time: 140
  response_start_time: 140
  response_end_time: 210
  baseline_ionomycin_start_time: 210
  baseline_ionomycin_end_time: 230
  ionomycin_start_time: 230
  ionomycin_end_time: 300
  cut_off_percentage: 0.05
