paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200928-Trex293CISD2-Caff-Ionomycin\\20200928-Trex293CISD2-Caff-Ionomycin-2"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_flexstation\\20200928-Trex293CISD2-Caff-Ionomycin\\20200928-Trex293CISD2-Caff-Ionomycin-2\\Response"
constants:
  example_bool: False
  response_start_time: 110
  response_end_time: 180
  ionomycin_start_time: 200
  ionomycin_end_time: 270
  cut_off_percentage: 0.05
filename: "KO7_extracted_ratio.csv"